language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
#install: "pip install -r requirements.txt"
# command to run tests
install:
 - pip install numpy scipy
 - python setup.py install
script:
   # Run the unit tests
 - py.test -m 'unit'
   # Run all the tests but those marked 'fortran', 'pandas', or 'unit'
 - py.test -m 'not fortran and not pandas and not unit'
   # If all basic tests pass, run the 'pandas' tests.
 - pip install -r requirements.txt
 - py.test -m 'pandas'
