language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
#install: "pip install -r requirements.txt"
# command to run tests
install:
 - pip install numpy scipy pandas
 - python setup.py install
script:
 - py.test -m 'not fortran'
